import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const p = await b.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 2 });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
await p.goto('http://127.0.0.1:4400/', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
console.log('cards:', await p.locator('.card').count());
console.log('names:', JSON.stringify(await p.locator('.card .name').allInnerTexts()));
console.log('indices:', JSON.stringify(await p.locator('.card .index').allInnerTexts()));
console.log('monet href:', await p.locator('.card[aria-label^="Monet"]').getAttribute('href'));
await p.screenshot({ path: process.argv[2] || '/tmp/site.png', fullPage: true });
const card = p.locator('.card[aria-label^="Monet"]');
await card.scrollIntoViewIfNeeded();
await p.waitForTimeout(400);
await card.screenshot({ path: (process.argv[2] || '/tmp/site.png').replace('.png', '-card.png') });
console.log(errs.length ? 'ERRORS:\n ' + errs.join('\n ') : 'no page errors');
await b.close();
